# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CGEV_DEV\cgevPipeline\maya\modules\archiveManager\scripts\ARCHIVE_MANAGER_UI.ui'
#
# Created: Tue May 02 13:30:55 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 245)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(470, 245))
        MainWindow.setMaximumSize(QtCore.QSize(470, 245))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 431, 171))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(5, 10, 411, 126))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_import = QtGui.QVBoxLayout()
        self.verticalLayout_import.setObjectName("verticalLayout_import")
        self.pushButton_import = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_import.setObjectName("pushButton_import")
        self.verticalLayout_import.addWidget(self.pushButton_import)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_imp_arc = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_imp_arc.setChecked(True)
        self.checkBox_imp_arc.setObjectName("checkBox_imp_arc")
        self.horizontalLayout_3.addWidget(self.checkBox_imp_arc)
        self.checkBox_imp_shd = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_imp_shd.setChecked(True)
        self.checkBox_imp_shd.setObjectName("checkBox_imp_shd")
        self.horizontalLayout_3.addWidget(self.checkBox_imp_shd)
        self.verticalLayout_import.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_import.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_import)
        self.verticalLayout_export = QtGui.QVBoxLayout()
        self.verticalLayout_export.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_export.setObjectName("verticalLayout_export")
        self.pushButton_export = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_export.setObjectName("pushButton_export")
        self.verticalLayout_export.addWidget(self.pushButton_export)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_exp_arc = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_exp_arc.setChecked(True)
        self.checkBox_exp_arc.setObjectName("checkBox_exp_arc")
        self.horizontalLayout_2.addWidget(self.checkBox_exp_arc)
        self.checkBox_exp_shd = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_exp_shd.setChecked(True)
        self.checkBox_exp_shd.setObjectName("checkBox_exp_shd")
        self.horizontalLayout_2.addWidget(self.checkBox_exp_shd)
        self.checkBox_exp_vc = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_exp_vc.setChecked(True)
        self.checkBox_exp_vc.setObjectName("checkBox_exp_vc")
        self.horizontalLayout_2.addWidget(self.checkBox_exp_vc)
        self.verticalLayout_export.addLayout(self.horizontalLayout_2)
        self.checkBox_exp_ani = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_exp_ani.setObjectName("checkBox_exp_ani")
        self.verticalLayout_export.addWidget(self.checkBox_exp_ani)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_frame = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_frame.setEnabled(True)
        self.label_frame.setObjectName("label_frame")
        self.horizontalLayout_4.addWidget(self.label_frame)
        self.lineEdit_start = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.horizontalLayout_4.addWidget(self.lineEdit_start)
        self.lineEdit_end = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_end.setObjectName("lineEdit_end")
        self.horizontalLayout_4.addWidget(self.lineEdit_end)
        self.verticalLayout_export.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_export.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_export)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 35, 321, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_mayaR = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_mayaR.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_mayaR.setObjectName("pushButton_mayaR")
        self.verticalLayout_3.addWidget(self.pushButton_mayaR)
        self.pushButton_clean = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.verticalLayout_3.addWidget(self.pushButton_clean)
        self.tabWidget.addTab(self.tab_2, "")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 195, 409, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ARCHIVE MANAGER", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_import.setText(QtGui.QApplication.translate("MainWindow", "IMPORT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_imp_arc.setText(QtGui.QApplication.translate("MainWindow", "ARCHIVE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_imp_shd.setText(QtGui.QApplication.translate("MainWindow", "SHADER", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export.setText(QtGui.QApplication.translate("MainWindow", "EXPORT", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_exp_arc.setText(QtGui.QApplication.translate("MainWindow", "ARCHIVE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_exp_shd.setText(QtGui.QApplication.translate("MainWindow", "SHADER", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_exp_vc.setText(QtGui.QApplication.translate("MainWindow", "VERTEX COLOR", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_exp_ani.setText(QtGui.QApplication.translate("MainWindow", "ANIMATION", None, QtGui.QApplication.UnicodeUTF8))
        self.label_frame.setText(QtGui.QApplication.translate("MainWindow", "start/end", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_start.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_end.setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "ARCHIVE I/O", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_mayaR.setText(QtGui.QApplication.translate("MainWindow", "REPLACE NODES", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clean.setText(QtGui.QApplication.translate("MainWindow", "CLEAN ARCHIVE NAME", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "ARCHIVE REPLACEMENT", None, QtGui.QApplication.UnicodeUTF8))

